export const SETTINGS_FOLDERS_EMOJIS = [
  {
    id: 'cat',
    names: ['cat'],
    native: '🐱',
    image: '1f431',
  },
  {
    id: 'book',
    names: ['book'],
    native: '📕',
    image: '1f4d5',
  },
  {
    id: 'money',
    names: ['money'],
    native: '💰',
    image: '1f4b0',
  },
  {
    id: 'flash',
    names: ['flash'],
    native: '📸',
    image: '26a1',
  },
  {
    id: 'game',
    names: ['game'],
    native: '🎮',
    image: '1f3ae',
  },
  {
    id: 'house',
    names: ['house'],
    native: '🏠',
    image: '1f3e0',
  },
  {
    id: 'bulb',
    names: ['bulb'],
    native: '💡',
    image: '1f4a1',
  },
  {
    id: 'thumbsup',
    names: ['thumbsup'],
    native: '👍',
    image: '1f44c',
  },
  {
    id: 'lock',
    names: ['lock'],
    native: '🔒',
    image: '1f512',
  },
  {
    id: 'heart',
    names: ['heart'],
    native: '❤️',
    image: '1f494',
  },
  {
    id: 'math',
    names: ['math'],
    native: '➕',
    image: '1f9ee',
  },
  {
    id: 'musical_note',
    names: ['musical_note'],
    native: '🎵',
    image: '1f3b5',
  },
  {
    id: 'art',
    names: ['art'],
    native: '🎨',
    image: '1f3a8',
  },
  {
    id: 'airplane',
    names: ['airplane'],
    native: '✈️',
    image: '2708',
  },
  {
    id: 'soccer',
    names: ['soccer'],
    native: '⚽️',
    image: '26bd',
  },
  {
    id: 'star',
    names: ['star'],
    native: '⭐',
    image: '2b50',
  },
  {
    id: 'mortar_board',
    names: ['mortar_board'],
    native: '🎓',
    image: '1f393',
  },
  {
    id: 'airplane_departure',
    names: ['airplane_departure'],
    native: '🛫',
    image: '1f6eb',
  },
  {
    id: 'bust',
    names: ['bust'],
    native: '👨‍💼',
    image: '1f464',
  },
  {
    id: 'bust_in_silhouette',
    names: ['bust_in_silhouette'],
    native: '👤',
    image: '1f464',
  },
  {
    id: 'busts_in_silhouette',
    names: ['busts_in_silhouette'],
    native: '👥',
    image: '1f465',
  },
  {
    id: 'speech_balloon',
    names: ['speech_balloon'],
    native: '💬',
    image: '1f4ac',
  },
  {
    id: 'white_check_mark',
    names: ['white_check_mark'],
    native: '✅',
    image: '2705',
  },
  {
    id: 'checkbox',
    names: ['checkbox'],
    native: '☑️',
    image: '2611',
  },
  {
    id: 'robot_face',
    names: ['robot_face'],
    native: '🤖',
    image: '1f916',
  },
  {
    id: 'file_folder',
    names: ['file_folder'],
    native: '📁',
    image: '1f4c1',
  },
];
